# Generated by Django 3.2.6 on 2021-08-22 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_type', models.CharField(choices=[('Информация', 'Обращение для получения информации'), ('Заказ', 'Обращение с целью оформить заказ'), ('Бизнес', 'Деловое предложение'), ('Жалоба', 'Жалобы и предложения')], default='Информация', max_length=30)),
            ],
        ),
    ]
