# Generated by Django 3.2.6 on 2021-08-22 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacttypes',
            options={'verbose_name': 'Тип обращений', 'verbose_name_plural': 'Типы обращений'},
        ),
        migrations.RemoveField(
            model_name='contacttypes',
            name='contact_type',
        ),
        migrations.AddField(
            model_name='contacttypes',
            name='type',
            field=models.CharField(max_length=30, null=True, verbose_name='Тип обращения'),
        ),
    ]
