# Generated by Django 3.2.6 on 2021-08-22 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_alter_contacttypes_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата обращения')),
            ],
            options={
                'verbose_name': 'Обращение',
                'verbose_name_plural': 'Журнал обращений',
            },
        ),
        migrations.CreateModel(
            name='UsersJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_info', models.TextField(blank=True, null=True, verbose_name='')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Журнал пользователей',
            },
        ),
    ]
