# Generated by Django 3.2.6 on 2021-08-22 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0004_contactjournal_usersjournal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersjournal',
            name='user_info',
            field=models.TextField(blank=True, null=True, verbose_name='Сведения о пользователе'),
        ),
    ]
