# Generated by Django 3.2.6 on 2021-08-23 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0008_auto_20210823_0240'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactjournal',
            name='contact_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='journal.contacttypes', verbose_name='Тип обращения'),
        ),
    ]
