# Generated by Django 3.2.6 on 2021-08-26 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0012_alter_contactjournal_staff_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactjournal',
            name='staff_name',
            field=models.CharField(choices=[('operator', 'operator')], max_length=50, null=True, verbose_name='Пользователь который принял обращение'),
        ),
    ]
