# Generated by Django 3.2.6 on 2021-08-28 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0014_alter_contactjournal_contact_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacttypes',
            name='type',
        ),
        migrations.AddField(
            model_name='contacttypes',
            name='type_name',
            field=models.CharField(max_length=200, null=True, verbose_name='Название обращения'),
        ),
    ]
